image: archlinux
packages:
  - sbcl
sources:
  - https://git.sr.ht/~theothornhill/lisp-ci
  - https://git.sr.ht/~theothornhill/advent
tasks:
  - setup: |
      ./lisp-ci/lisp-ci.sh
      mv ~/advent ~/quicklisp/local-projects/
      cd ~/quicklisp/local-projects/advent
  - test: |
      cd ~/quicklisp/local-projects/advent
      ./test.sh
